<?php

namespace Web\EntityBundle\Repository;

/**
 * AdditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionRepository extends \Doctrine\ORM\EntityRepository
{
}
