<?php

namespace Web\EntityBundle\Repository;

/**
 * CancellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancellingRepository extends \Doctrine\ORM\EntityRepository
{
}
