<?php

namespace Web\EntityBundle\Repository;

/**
 * CommitHistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitHistoricRepository extends \Doctrine\ORM\EntityRepository
{
    public function  getByparam($data, $limit=20, $page=1, $count=false )
    {
        $query = $this->createQueryBuilder('a');
        if($count)
        {
            $query->select('count(a.id)');
            return $query->getQuery()->getSingleScalarResult();
        }

        $query->select(['a','t','pl','pr','u'])
            ->leftJoin('a.task','t')
            ->leftJoin('t.planning','pl')
            ->leftJoin('pl.project','pr')
            ->leftJoin('pr.user','u');


        if($data!=null)
        {
            /*$parameters['title']='%'.$data['title'].'%';
            $parameters['status']='%'.$data['status'].'%';
            */
            $parameters['project_id']=$data['project_id'];
            $parameters['user_id']=$data['user_id'];
            $parameters['task_id']=$data['task_id'];

            /*$query->Where('pr.title LIKE :title OR pr.title IS NULL');
            $query->Where('pr.status LIKE :status OR pr.status IS NULL');
            */
            $query->andWhere('pr.id =:project_id OR  pr.id IS NULL');
            $query->andWhere('u.id =:user_id OR  u.id IS NULL');
            $query->andWhere('t.id =:task_id OR  t.id IS NULL');
            $query->setParameters($parameters);
            $query->addOrderBy('a.id','desc');
            if($limit)
            {
                $page=$page<1?1:$page;
                $query->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
            }
        }

        return $query->getQuery()->getResult();

    }

    public function  getByparamUserAndProject($data, $limit=20, $page=1, $count=false )
    {
        $query = $this->createQueryBuilder('a');
        if($count)
        {
            $query->select('count(a.id)');
            return $query->getQuery()->getSingleScalarResult();
        }

        $query->select(['a','t','pl','pr','u'])
            ->leftJoin('a.task','t')
            ->leftJoin('t.planning','pl')
            ->leftJoin('pl.project','pr')
            ->leftJoin('pr.user','u');


        if($data!=null)
        {

            $parameters['project_id']=$data['project_id'];
            $parameters['user_id']=$data['user_id'];

            /*$query->Where('pr.title LIKE :title OR pr.title IS NULL');
            $query->Where('pr.status LIKE :status OR pr.status IS NULL');
            */
            $query->andWhere('pr.id =:project_id OR  pr.id IS NULL');
            $query->andWhere('u.id =:user_id OR  u.id IS NULL');
            $query->setParameters($parameters);
            $query->addOrderBy('a.id','desc');
            if($limit)
            {
                $page=$page<1?1:$page;
                $query->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
            }
        }

        return $query->getQuery()->getResult();

    }
    public function  getByparamProject($data, $limit=20, $page=1, $count=false )
    {
        $query = $this->createQueryBuilder('a');
        if($count)
        {
            $query->select('count(a.id)');
            return $query->getQuery()->getSingleScalarResult();
        }

        $query->select(['a','t','pl','pr','u'])
            ->leftJoin('a.task','t')
            ->leftJoin('t.planning','pl')
            ->leftJoin('pl.project','pr')
            ->leftJoin('pr.user','u');


        if($data!=null)
        {

            $parameters['project_id']=$data['project_id'];


            $query->andWhere('pr.id =:project_id OR  pr.id IS NULL');
            $query->setParameters($parameters);
            $query->addOrderBy('a.id','desc');
            if($limit)
            {
                $page=$page<1?1:$page;
                $query->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
            }
        }

        return $query->getQuery()->getResult();

    }
    public function  getByparamUser($data, $limit=20, $page=1, $count=false )
    {
        $query = $this->createQueryBuilder('a');
        if($count)
        {
            $query->select('count(a.id)');
            return $query->getQuery()->getSingleScalarResult();
        }

        $query->select(['a','t','pl','pr','u'])
            ->leftJoin('a.task','t')
            ->leftJoin('t.planning','pl')
            ->leftJoin('pl.project','pr')
            ->leftJoin('pr.user','u');


        if($data!=null)
        {

            $parameters['user_id']=$data['user_id'];

            $query->andWhere('u.id =:user_id OR  u.id IS NULL');
            $query->setParameters($parameters);
            $query->addOrderBy('a.id','desc');
            if($limit)
            {
                $page=$page<1?1:$page;
                $query->setFirstResult(($page-1)*$limit)->setMaxResults($limit);
            }
        }

        return $query->getQuery()->getResult();

    }
}
