<?php

namespace Web\EntityBundle\Repository;

/**
 * CommitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser($id)
    {

        $query = $this->createQueryBuilder('a');
        $query->select(['a','p','u'])
            ->leftJoin('a.participator','p')
            ->leftJoin('p.user','u')
            ->Where('u.id =:p_id ')
            ->setParameter('p_id',$id)
            ->addOrderBy('a.id','desc');

        return $query->getQuery()->getResult();

    }
}
