<?php

namespace Web\EntityBundle\Repository;

/**
 * CommitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitRepository extends \Doctrine\ORM\EntityRepository
{
}
