<?php

namespace Web\EntityBundle\Repository;

/**
 * FileProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
