<?php

namespace Web\EntityBundle\Repository;

/**
 * HistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricRepository extends \Doctrine\ORM\EntityRepository
{
}
