<?php

namespace Web\EntityBundle\Repository;

use Web\EntityBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStaff()
    {
        $array = [];

        $query = $this->_em->createQuery('SELECT u FROM EntityBundle:User u');
        $result = $query->getResult();

        /** @var User $item */
        foreach ($result as $item)
        {
            if($item->hasRole(User::ROLE_SUPER_ADMIN) || $item->hasRole(User::ROLE_ADMIN) || $item->hasRole(User::ROLE_STAFF))
            {
                $array[] = $item;
            }
        }

        return $array;
    }


    public function findActifUser()
    {

        $query = $this->createQueryBuilder('a');
        $query->select(['a'])
              ->Where('a.active is null ')
              ->orWhere('a.active = true ')
              ->addOrderBy('a.id','desc');

        return $query->getQuery()->getResult();

    }
}
