<?php

namespace Web\EntityBundle\Repository;

/**
 * BaseInterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseInterfaceRepository extends \Doctrine\ORM\EntityRepository
{
}
