<?php

namespace Web\EntityBundle\Repository;

/**
 * CommitHistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitHistoricRepository extends \Doctrine\ORM\EntityRepository
{
}
