<?php

namespace Web\EntityBundle\Repository;

/**
 * ParticipatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipatorRepository extends \Doctrine\ORM\EntityRepository
{
}
